"""Remap card topic_keys to match revamped topic graphs (v3)

Revision ID: b4c2d5e6f8a9
Revises: a3b1c4d5e6f7
Create Date: 2026-03-12 12:00:00.000000+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "b4c2d5e6f8a9"
down_revision = "a3b1c4d5e6f7"
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# Keyword-based mapping: (subject, new_topic_key, LIKE patterns)
#
# For each row in `cards` where topic_key matches one of the LIKE patterns,
# UPDATE topic_key = new_topic_key.
#
# Patterns are ordered most-specific-first within each subject.
# The migration is idempotent: re-running it on already-migrated rows
# is a no-op (the row already matches a canonical key).
# ---------------------------------------------------------------------------

_CN_MAPPING: list[tuple[str, list[str]]] = [
    # --- Transport layer: TCP ---
    (
        "cn:congestion-control",
        [
            "cn:%congestion%",
            "cn:%four-senders%",
        ],
    ),
    (
        "cn:tcp-connection-management",
        [
            "cn:%tcp-connection%",
            "cn:%three-way-handshake%",
            "cn:%syn-flood%",
        ],
    ),
    (
        "cn:tcp-rtt-and-timeout",
        [
            "cn:%round-trip-time%",
            "cn:%estimating-the-round%",
            "cn:%retransmission-timeout%",
            "cn:%doubling-the-timeout%",
            "cn:%timeout-interval%",
        ],
    ),
    (
        "cn:tcp-reliable-transfer",
        [
            "cn:%tcp-reliable%",
            "cn:%fast-retransmit%",
            "cn:%tcp-sender%",
            "cn:%go-back-n-or-selective%",
        ],
    ),
    (
        "cn:tcp-segment-structure",
        [
            "cn:%tcp-segment%",
            "cn:%sequence-number%",
            "cn:%acknowledgment-number%",
        ],
    ),
    (
        "cn:pipelining-gbn-sr",
        [
            "cn:%pipelined%",
            "cn:%go-back-n%",
            "cn:%selective-repeat%",
            "cn:%gbn%",
        ],
    ),
    (
        "cn:reliable-data-transfer",
        [
            "cn:%reliable-data-transfer%",
            "cn:%rdt2%",
            "cn:%rdt3%",
            "cn:%building-a-reliable%",
        ],
    ),
    (
        "cn:udp",
        [
            "cn:%udp%",
        ],
    ),
    (
        "cn:multiplexing-demultiplexing",
        [
            "cn:%multiplexing%",
            "cn:%demultiplexing%",
            "cn:%web-servers-and-tcp%",
        ],
    ),
    (
        "cn:transport-layer",
        [
            "cn:%transport-layer%",
            "cn:%relationship-between-transport%",
            "cn:%overview-of-the-transport%",
        ],
    ),
    # --- Application layer ---
    (
        "cn:cdn",
        [
            "cn:%content-distribution%",
            "cn:%cluster-selection%",
            "cn:%netflix%",
            "cn:%youtube%",
            "cn:%cdn%",
        ],
    ),
    (
        "cn:video-streaming",
        [
            "cn:%internet-video%",
            "cn:%streaming-and-dash%",
            "cn:%http-streaming%",
            "cn:%dash%",
        ],
    ),
    (
        "cn:peer-to-peer",
        [
            "cn:%p2p%",
            "cn:%peer-to-peer%",
            "cn:%bittorrent%",
            "cn:%scalability-of-p2p%",
        ],
    ),
    (
        "cn:dns",
        [
            "cn:%dns%",
        ],
    ),
    (
        "cn:web-caching",
        [
            "cn:%web-cach%",
            "cn:%conditional-get%",
            "cn:%proxy%",
        ],
    ),
    (
        "cn:cookies-and-state",
        [
            "cn:%cookie%",
            "cn:%user-server-interaction%",
        ],
    ),
    (
        "cn:http",
        [
            "cn:%http%",
            "cn:%overview-of-http%",
            "cn:%non-persistent%",
            "cn:%persistent-connection%",
            "cn:%request-message%",
            "cn:%response-message%",
            "cn:%server-push%",
        ],
    ),
    (
        "cn:application-layer-protocols",
        [
            "cn:%application-layer-protocol%",
        ],
    ),
    (
        "cn:transport-services",
        [
            "cn:%transport-services%",
            "cn:%services-not-provided%",
            "cn:%timing%",
        ],
    ),
    (
        "cn:client-server-and-sockets",
        [
            "cn:%processes-communicating%",
            "cn:%client-and-server%",
            "cn:%interface-between-the-process%",
            "cn:%addressing-process%",
            "cn:%socket%",
        ],
    ),
    (
        "cn:application-layer",
        [
            "cn:%application%",
            "cn:%network-application-architecture%",
        ],
    ),
    # --- Network infrastructure ---
    (
        "cn:network-security-intro",
        [
            "cn:%bad-guys%",
            "cn:%malware%",
            "cn:%ddos%",
            "cn:%sniff%",
            "cn:%masquerade%",
            "cn:%firewall%",
            "cn:%tls%",
            "cn:%ssl%",
            "cn:%security%",
            "cn:%ipsec%",
            "cn:%cryptograph%",
            "cn:%cipher%",
            "cn:%digital-signature%",
            "cn:%rsa%",
            "cn:%authentication%",
            "cn:%message-integrity%",
        ],
    ),
    (
        "cn:protocol-layering",
        [
            "cn:%layered-architecture%",
            "cn:%protocol-layering%",
            "cn:%encapsulation%",
            "cn:%osi%",
        ],
    ),
    (
        "cn:physical-layer",
        [
            "cn:%physical-layer%",
        ],
    ),
    (
        "cn:link-layer",
        [
            "cn:%link-layer%",
            "cn:%ethernet%",
            "cn:%mac-%",
            "cn:%arp%",
            "cn:%error-detection%",
            "cn:%error-correction%",
            "cn:%crc%",
            "cn:%switched-local%",
            "cn:%random-access%",
            "cn:%csma%",
            "cn:%aloha%",
            "cn:%taking-turns%",
            "cn:%polling%",
        ],
    ),
    (
        "cn:network-layer",
        [
            "cn:%network-layer%",
            "cn:%ip-address%",
            "cn:%ipv4%",
            "cn:%ipv6%",
            "cn:%cidr%",
            "cn:%subnet%",
            "cn:%nat%",
            "cn:%dhcp%",
            "cn:%icmp%",
            "cn:%datagram%",
            "cn:%forwarding%",
            "cn:%routing%",
            "cn:%link-state%",
            "cn:%distance-vector%",
            "cn:%ospf%",
            "cn:%bgp%",
            "cn:%sdn%",
            "cn:%openflow%",
            "cn:%router%",
            "cn:%autonomous-system%",
            "cn:%route-selection%",
        ],
    ),
    (
        "cn:delay-and-loss",
        [
            "cn:%delay%",
            "cn:%packet-loss%",
            "cn:%queuing%",
            "cn:%propagation%",
            "cn:%traceroute%",
            "cn:%throughput%",
            "cn:%end-to-end%",
            "cn:%end-system%",
        ],
    ),
    (
        "cn:network-core",
        [
            "cn:%network-of-networks%",
            "cn:%forwarding-table%",
            "cn:%packet-switch%",
            "cn:%circuit-switch%",
            "cn:%store-and-forward%",
            "cn:%isp%",
            "cn:%network-core%",
        ],
    ),
    (
        "cn:physical-media",
        [
            "cn:%twisted-pair%",
            "cn:%coaxial%",
            "cn:%fiber-optic%",
            "cn:%radio-channel%",
            "cn:%satellite%",
            "cn:%wide-area-wireless%",
            "cn:%physical-media%",
        ],
    ),
    (
        "cn:network-edge",
        [
            "cn:%network-edge%",
            "cn:%access-network%",
            "cn:%access-in-the-enterprise%",
            "cn:%dsl%",
            "cn:%cable%",
            "cn:%ftth%",
        ],
    ),
    (
        "cn:protocols",
        [
            "cn:%what-is-a-protocol%",
            "cn:%network-protocols%",
        ],
    ),
    (
        "cn:internet-overview",
        [
            "cn:%what-is-the-internet%",
            "cn:%chapter-1-introduction%",
            "cn:%services-description%",
            "cn:%nuts-and-bolts%",
            "cn:%road-mapping%",
            "cn:%history-of-computer%",
        ],
    ),
]

_DBMS_MAPPING: list[tuple[str, list[str]]] = [
    (
        "dbms:web-architectures",
        [
            "dbms:%web-architectures%",
            "dbms:%three-tier%",
            "dbms:%distributed%",
        ],
    ),
    (
        "dbms:application-dev",
        [
            "dbms:%application-dev%",
            "dbms:%jdbc%",
            "dbms:%odbc%",
            "dbms:%embedded-sql%",
            "dbms:%cursor%",
            "dbms:%sqlj%",
            "dbms:%dynamic-sql%",
        ],
    ),
    (
        "dbms:transactions",
        [
            "dbms:%transaction%",
            "dbms:%acid%",
            "dbms:%concurrency%",
            "dbms:%recovery%",
            "dbms:%serializab%",
            "dbms:%lock%",
            "dbms:%two-phase%",
            "dbms:%timestamp%",
            "dbms:%log%",
            "dbms:%undo%",
            "dbms:%redo%",
            "dbms:%wal%",
            "dbms:%deadlock%",
            "dbms:%phantom%",
            "dbms:%isolation%",
            "dbms:%schedule%",
            "dbms:%commit%",
            "dbms:%abort%",
            "dbms:%rollback%",
        ],
    ),
    (
        "dbms:storage-and-indexing",
        [
            "dbms:%storage%",
            "dbms:%index%",
            "dbms:%b-tree%",
            "dbms:%b-plus%",
            "dbms:%hash%",
            "dbms:%heap-file%",
            "dbms:%sorted-file%",
            "dbms:%disk%",
            "dbms:%page%",
            "dbms:%buffer%",
            "dbms:%clustered%",
        ],
    ),
    (
        "dbms:views",
        [
            "dbms:%view%",
            "dbms:%data-independence%",
        ],
    ),
    (
        "dbms:triggers",
        [
            "dbms:%trigger%",
            "dbms:%active-database%",
        ],
    ),
    (
        "dbms:nested-queries",
        [
            "dbms:%nested%",
            "dbms:%subquer%",
            "dbms:%set-operation%",
            "dbms:%exists%",
            "dbms:%in-operator%",
            "dbms:%union%",
            "dbms:%intersect%",
            "dbms:%except%",
        ],
    ),
    (
        "dbms:sql-queries",
        [
            "dbms:%sql-quer%",
            "dbms:%select%",
            "dbms:%join%",
            "dbms:%aggregat%",
            "dbms:%group-by%",
            "dbms:%having%",
            "dbms:%where%",
            "dbms:%order-by%",
            "dbms:%like%",
            "dbms:%null%",
            "dbms:%distinct%",
            "dbms:%rename%",
            "dbms:%string-operation%",
            "dbms:%functions-and-procedures%",
        ],
    ),
    (
        "dbms:schema-refinement",
        [
            "dbms:%schema-refinement%",
            "dbms:%normaliz%",
            "dbms:%normal-form%",
            "dbms:%functional-depend%",
            "dbms:%decomposition%",
            "dbms:%bcnf%",
            "dbms:%3nf%",
            "dbms:%2nf%",
            "dbms:%1nf%",
            "dbms:%closure%",
            "dbms:%lossless%",
            "dbms:%dependency-preserv%",
        ],
    ),
    (
        "dbms:integrity-constraints",
        [
            "dbms:%integrity%",
            "dbms:%foreign-key%",
            "dbms:%primary-key%",
            "dbms:%assertion%",
            "dbms:%check-%",
            "dbms:%referential%",
            "dbms:%domain-constraint%",
        ],
    ),
    (
        "dbms:sql-ddl",
        [
            "dbms:%sql-ddl%",
            "dbms:%schema-definition%",
            "dbms:%create-table%",
            "dbms:%alter-table%",
            "dbms:%drop-table%",
            "dbms:%data-definition%",
            "dbms:%basic-schema%",
        ],
    ),
    (
        "dbms:relational-algebra",
        [
            "dbms:%relational-algebra%",
            "dbms:%project%",
            "dbms:%cartesian%",
            "dbms:%natural-join%",
            "dbms:%division%",
            "dbms:%relational-calculus%",
            "dbms:%tuple-relational%",
            "dbms:%domain-relational%",
        ],
    ),
    (
        "dbms:er-to-relational-mapping",
        [
            "dbms:%er-to-relational%",
            "dbms:%mapping-er%",
            "dbms:%converting-er%",
        ],
    ),
    (
        "dbms:er-advanced",
        [
            "dbms:%er-advanced%",
            "dbms:%weak-entit%",
            "dbms:%aggregation%",
            "dbms:%hierarch%",
            "dbms:%specialization%",
            "dbms:%generalization%",
            "dbms:%isa%",
        ],
    ),
    (
        "dbms:er-constraints",
        [
            "dbms:%er-constraint%",
            "dbms:%participation%",
            "dbms:%cardinality%",
            "dbms:%key-constraint%",
        ],
    ),
    (
        "dbms:er-model",
        [
            "dbms:%er-model%",
            "dbms:%entity-relationship%",
            "dbms:%entity-set%",
            "dbms:%relationship-set%",
            "dbms:%attribute%",
        ],
    ),
    (
        "dbms:conceptual-design",
        [
            "dbms:%conceptual%",
            "dbms:%database-design%",
        ],
    ),
    (
        "dbms:relational-model",
        [
            "dbms:%relational-model%",
            "dbms:%relation-%",
            "dbms:%tuple%",
            "dbms:%schema%",
        ],
    ),
    (
        "dbms:intro-to-dbms",
        [
            "dbms:%intro%",
            "dbms:%database-management%",
            "dbms:%database-system%",
            "dbms:%data-model%",
            "dbms:%database-language%",
        ],
    ),
]

_OS_MAPPING: list[tuple[str, list[str]]] = [
    (
        "os:security-and-protection",
        [
            "os:%security%",
            "os:%protection%",
            "os:%access-control%",
            "os:%authentication%",
            "os:%trusted%",
            "os:%sandbox%",
            "os:%capability%",
            "os:%acl%",
        ],
    ),
    (
        "os:deadlock",
        [
            "os:%deadlock%",
            "os:%banker%",
            "os:%ostrich%",
            "os:%resource-allocation-graph%",
            "os:%starvation%",
            "os:%livelock%",
        ],
    ),
    (
        "os:file-systems",
        [
            "os:%file-system%",
            "os:%file-allocation%",
            "os:%directory%",
            "os:%inode%",
            "os:%fat%",
            "os:%ext%",
            "os:%ntfs%",
            "os:%free-space%",
            "os:%journaling%",
            "os:%mount%",
            "os:%link%",
        ],
    ),
    (
        "os:input-output",
        [
            "os:%input-output%",
            "os:%i-o%",
            "os:%io-%",
            "os:%dma%",
            "os:%interrupt%",
            "os:%device-driver%",
            "os:%disk-scheduling%",
            "os:%raid%",
            "os:%ssd%",
            "os:%block-device%",
            "os:%character-device%",
        ],
    ),
    (
        "os:virtual-memory",
        [
            "os:%virtual-memory%",
            "os:%page-replacement%",
            "os:%page-fault%",
            "os:%page-table%",
            "os:%paging%",
            "os:%page-buffer%",
            "os:%tlb%",
            "os:%demand-paging%",
            "os:%thrashing%",
            "os:%working-set%",
            "os:%lru%",
            "os:%fifo%",
            "os:%clock-algorithm%",
            "os:%optimal%",
            "os:%frame-allocation%",
            "os:%copy-on-write%",
            "os:%memory-mapped%",
        ],
    ),
    (
        "os:memory-management",
        [
            "os:%memory-management%",
            "os:%address-space%",
            "os:%segmentation%",
            "os:%base-and-limit%",
            "os:%swapping%",
            "os:%fragmentation%",
            "os:%memory-allocation%",
            "os:%contiguous%",
            "os:%buddy-system%",
            "os:%slab%",
            "os:%free-list%",
            "os:%first-fit%",
            "os:%best-fit%",
            "os:%worst-fit%",
        ],
    ),
    (
        "os:synchronization",
        [
            "os:%synchronization%",
            "os:%mutex%",
            "os:%semaphore%",
            "os:%monitor%",
            "os:%race-condition%",
            "os:%critical-section%",
            "os:%peterson%",
            "os:%bakery%",
            "os:%spinlock%",
            "os:%condition-variable%",
            "os:%producer-consumer%",
            "os:%readers-writers%",
            "os:%dining-philosopher%",
            "os:%barrier%",
            "os:%test-and-set%",
            "os:%compare-and-swap%",
            "os:%futex%",
        ],
    ),
    (
        "os:scheduling",
        [
            "os:%scheduling%",
            "os:%round-robin%",
            "os:%shortest-job%",
            "os:%priority-%",
            "os:%multilevel%",
            "os:%fcfs%",
            "os:%sjf%",
            "os:%srtf%",
            "os:%cfs%",
            "os:%real-time%",
            "os:%preemptive%",
            "os:%non-preemptive%",
            "os:%cpu-bound%",
            "os:%io-bound%",
        ],
    ),
    (
        "os:inter-process-communication",
        [
            "os:%inter-process%",
            "os:%ipc%",
            "os:%shared-memory%",
            "os:%message-passing%",
            "os:%pipe%",
            "os:%signal%",
            "os:%remote-procedure%",
            "os:%rpc%",
            "os:%client-server%",
        ],
    ),
    (
        "os:threads",
        [
            "os:%thread%",
            "os:%pthread%",
            "os:%user-level-thread%",
            "os:%kernel-thread%",
            "os:%multithread%",
            "os:%concurren%",
        ],
    ),
    (
        "os:processes",
        [
            "os:%process%",
            "os:%fork%",
            "os:%exec%",
            "os:%wait%",
            "os:%context-switch%",
            "os:%pcb%",
            "os:%process-control%",
            "os:%process-state%",
            "os:%process-creation%",
            "os:%process-termination%",
        ],
    ),
    (
        "os:virtual-machines",
        [
            "os:%virtual-machine%",
            "os:%hypervisor%",
            "os:%vmm%",
            "os:%container%",
            "os:%docker%",
        ],
    ),
    (
        "os:os-structure",
        [
            "os:%os-structure%",
            "os:%monolithic%",
            "os:%microkernel%",
            "os:%layered-%",
            "os:%modular%",
            "os:%kernel-%",
        ],
    ),
    (
        "os:system-calls",
        [
            "os:%system-call%",
            "os:%syscall%",
            "os:%posix%",
            "os:%api-%",
        ],
    ),
    (
        "os:os-concepts",
        [
            "os:%os-concept%",
            "os:%operating-system-concept%",
        ],
    ),
    (
        "os:os-zoo",
        [
            "os:%os-zoo%",
            "os:%operating-system-zoo%",
        ],
    ),
    (
        "os:computer-hardware-basics",
        [
            "os:%computer-hardware%",
            "os:%hardware-%",
            "os:%cpu-%",
            "os:%bus-%",
            "os:%boot%",
        ],
    ),
    (
        "os:history-of-os",
        [
            "os:%history%",
        ],
    ),
    (
        "os:introduction",
        [
            "os:%introduction%",
            "os:%what-is-an-operating%",
        ],
    ),
]


def _build_update_sql(
    table: str, col: str, mapping: list[tuple[str, list[str]]]
) -> list[str]:
    """Build a list of UPDATE statements from a mapping."""
    stmts: list[str] = []
    for new_key, patterns in mapping:
        conditions = " OR ".join(f"{col} LIKE '{p}'" for p in patterns)
        stmts.append(
            f"UPDATE {table} SET {col} = '{new_key}' "
            f"WHERE {col} != '{new_key}' AND ({conditions})"
        )
    return stmts


def upgrade() -> None:
    conn = op.get_bind()

    # Remap cards.topic_key
    for mapping in [_CN_MAPPING, _DBMS_MAPPING, _OS_MAPPING]:
        for stmt in _build_update_sql("cards", "topic_key", mapping):
            conn.execute(sa.text(stmt))

    # Remap user_topic_mastery.topic_key
    for mapping in [_CN_MAPPING, _DBMS_MAPPING, _OS_MAPPING]:
        for stmt in _build_update_sql("user_topic_mastery", "topic_key", mapping):
            conn.execute(sa.text(stmt))

    # Remap user_topic_swot.topic_key
    for mapping in [_CN_MAPPING, _DBMS_MAPPING, _OS_MAPPING]:
        for stmt in _build_update_sql("user_topic_swot", "topic_key", mapping):
            conn.execute(sa.text(stmt))

    # Clean up orphaned topic_taxonomy_nodes and topic_prerequisites
    # (handled by sync_topic_dependency_graph.py --replace-subject)


def downgrade() -> None:
    # Remapping is lossy (many-to-one); cannot automatically reverse.
    # To restore, re-seed cards from the validated JSONL data.
    pass
